### PR TITLE
Updated to version 1.3

### PR DESCRIPTION
**Pull request by REDECODE**
Based on traex/RippleEffect - Tag: v1.3

Main differences from version 1.1:
Fixed rectangular animation.
Fixed OnClick (event not fired)
Added OnLongPress managed
Added event OnCompletition

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Thanks for this PR. Could you please fix formatting of the code you have added? It is indented way more than the rest.

**Comment by REDECODE** [comment]
Ok, I removed all commented code and formatted the code using XamarinStudio "format document" function

**Comment by Cheesebaron** [comment]
Oh wow, it looks even more horrible now. I'll just cherry pick the first one and format it myself...

**Comment by REDECODE** [comment]
probably because XamarinStudio by default use tab instead of space for indentation

**Comment by Cheesebaron** [comment]
This has been manually merged. Thanks :)

**Pull request closed without merging**
